% Import the raw data in brainstorm

% Input files (raw data import)
sFiles = {...
    'yourData.mat'};

% Resample: 512Hz
sFiles = bst_process('CallProcess', 'process_resample', sFiles, [], ...
    'freq',     512, ...
    'read_all', 1);

% Band-pass:0.5Hz-45Hz
sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
    'sensortypes', 'EEG', ...
    'highpass',    0.5, ...
    'lowpass',     45, ...
    'tranband',    0, ...
    'attenuation', 'strict', ...  % 60dB
    'ver',         '2019', ...
    'mirror',      0, ...
    'read_all',    1);

% ICA components: Picard
sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
    'timewindow',   [], ...
    'eventname',    '', ...
    'eventtime',    [-0.1992, 0.1992], ...
    'sensortypes',  '', ...
    'ignorebad',    1, ...
    'bandpass',     [0, 0], ...
    'resample',     0, ...
    'usessp',       1, ...
    'method',       'picard', ... 
    'nicacomp',     50, ...
    'icasort',      '', ...
    'saveerp',      1);

% ICA components: Picard + EKG Channel
sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
    'timewindow',   [], ...
    'eventname',    '', ...
    'eventtime',    [-0.1992, 0.1992], ...
    'sensortypes',  '', ...
    'ignorebad',    1, ...
    'bandpass',     [0, 0], ...
    'resample',     0, ...
    'usessp',       1, ...
    'method',       'picard', ...
    'nicacomp',     0, ...
    'icasort',      'EKG', ...
    'saveerp',      1);


%% Inspect the data visually 
% Then applied
% Power spectrum density
sFiles = bst_process('CallProcess', 'process_psd', sFiles, [], ...
    'timewindow',  [], ...
    'win_length',  2, ...
    'win_overlap', 50, ...
    'units',       'physical', ...  % Physical: U2/Hz
    'sensortypes', 'MEG, EEG', ...
    'win_std',     0, ...
    'edit',        struct(...
         'Comment',         'Power,FreqBands', ...
         'TimeBands',       [], ...
         'Freqs',           {{'delta', '1, 4', 'mean'; ...
         'theta', '4, 8', 'mean'; ...
         'alpha', '8, 12', 'mean'; ...
         'beta', '12, 30', 'mean'; ...
         'gamma', '30, 45', 'mean'}}, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));

